import { createSlice } from "@reduxjs/toolkit";

// Define initial state for the user slice
const initialState = {
  currentUser: null, // Initially no user is logged in
  error: null, // No error initially
  loading: false, // Not loading initially
};

// Define the user slice
const userSlice = createSlice({
  name: "user", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer for login start action
    loginStart: (state) => {
      state.loading = true; // Set loading to true
      state.error = null; // Clear any previous error
    },
    // Reducer for login success action
    loginSuccess: (state, action) => {
      state.currentUser = action.payload; // Set current user based on payload
      state.loading = false; // Set loading to false
      state.error = null; // Clear any previous error
    },
    // Reducer for login failure action
    loginFailure: (state, action) => {
      state.error = action.payload; // Set error message based on payload
      state.loading = false; // Set loading to false
    },
  },
});

// Extract action creators from the slice
export const { loginStart, loginSuccess, loginFailure } = userSlice.actions;

// Export the reducer generated by createSlice
export default userSlice.reducer;
